apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: NodePort
  selector:
    app: grafana
    tier: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
